---
- hosts: all

  tasks:
    - apt_repository:
        repo: "ppa:jonathonf/vim"
      when: ansible_distribution == 'Ubuntu'
      become: yes

    - package: name=vim-nox state=latest
      become: yes

    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - file: path=~/.vim/{{ item }} state=directory recurse=Yes
      with_items:
        - autoload
        - colors

    - get_url:
        force: yes
        dest: ~/.vim/autoload/plug.vim
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
